### ISSUE TITLE
PLEASE don't make MCPI die.

### ISSUE THREAD

**Issue by therealsimon14** [MCPI-Revival/minecraft-4k-reborn#1]
Hi!

I understand that this is probably a new project, but could you please keep mcpi alive at least?
Sure keep this project the main priority, but please keep mcpi at least slightly maintained.

I really don't want mcpi to die, as it is the reason why I came to this community.

-Thanks

Grimet(#9620)

**Comment by nobody5050** [comment]
Outdated, mc4k is the new project direction.

**Comment by therealsimon14** [comment]
Wow, ok.

**Comment by Binkers-Gaming** [comment]
Minecraft 4k Is going to need to be called Minecraft 4000k After They are done

**Comment by Bigjango13** [comment]
MC400k > MCPI-Revival

**Comment by therealsimon14** [comment]
:(
