### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by Bigjango13** [MCPI-Revival/minecraft-4k-reborn#2]
This project seems very real and not a like a joke at all. But I would like some documentation for me to not read and then complain about issues that were addressed in the documentation (while you're at it could you also add an FAQ channel to the discord for me to also not read?).

**Comment by TheBrokenRail** [comment]
Use Gradle! `./gradlew build`!

**Comment by TheBrokenRail** [comment]
And the wiki has controls: https://minecraft.fandom.com/wiki/Minecraft_4k
